<?php

use Illuminate\Database\Seeder;

class DealersTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('dealers')->insert([
			['id' => '1', 'name' => 'RPM Trailer Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '3', 'name' => 'Trailer World', 'created_at' => now(), 'updated_at' => now()],
			['id' => '4', 'name' => 'Rezner Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '5', 'name' => 'Flying A Motorsports', 'created_at' => now(), 'updated_at' => now()],
			['id' => '6', 'name' => 'American Airworks', 'created_at' => now(), 'updated_at' => now()],
			['id' => '10', 'name' => 'inTech Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '15', 'name' => 'The Trailer Shop', 'created_at' => now(), 'updated_at' => now()],
			['id' => '20', 'name' => 'Ridenow Powersports', 'created_at' => now(), 'updated_at' => now()],
			['id' => '26', 'name' => 'Eldorado Trailer Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '54', 'name' => 'Alaska Communications Systems', 'created_at' => now(), 'updated_at' => now()],
			['id' => '60', 'name' => 'Allo Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '61', 'name' => 'Alma Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '68', 'name' => 'Power Program', 'created_at' => now(), 'updated_at' => now()],
			['id' => '72', 'name' => 'Appalachian Power Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '77', 'name' => 'Applied Research Associates', 'created_at' => now(), 'updated_at' => now()],
			['id' => '135', 'name' => 'Cable One Kirksville  MO', 'created_at' => now(), 'updated_at' => now()],
			['id' => '136', 'name' => 'CableTel Services', 'created_at' => now(), 'updated_at' => now()],
			['id' => '153', 'name' => 'National Technologies', 'created_at' => now(), 'updated_at' => now()],
			['id' => '155', 'name' => 'Grande Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '159', 'name' => 'GoFrac  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '180', 'name' => 'Cedar Falls Utilities', 'created_at' => now(), 'updated_at' => now()],
			['id' => '214', 'name' => 'TCS Communications FL', 'created_at' => now(), 'updated_at' => now()],
			['id' => '215', 'name' => 'FiberOptic.com', 'created_at' => now(), 'updated_at' => now()],
			['id' => '222', 'name' => 'Comcast Cable Houston  TX', 'created_at' => now(), 'updated_at' => now()],
			['id' => '223', 'name' => 'Comcast Cable PA', 'created_at' => now(), 'updated_at' => now()],
			['id' => '226', 'name' => 'Communications Construction Group', 'created_at' => now(), 'updated_at' => now()],
			['id' => '228', 'name' => 'Comporium Communications SC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '231', 'name' => 'Consolidated Communications Corporation', 'created_at' => now(), 'updated_at' => now()],
			['id' => '244', 'name' => 'Cutts Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '247', 'name' => 'Andrea Contracting', 'created_at' => now(), 'updated_at' => now()],
			['id' => '262', 'name' => 'Nesco', 'created_at' => now(), 'updated_at' => now()],
			['id' => '268', 'name' => 'DFT Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '277', 'name' => 'DR Splicing Services  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '290', 'name' => 'Emery Telcom', 'created_at' => now(), 'updated_at' => now()],
			['id' => '295', 'name' => 'Fairpoint Communications ME', 'created_at' => now(), 'updated_at' => now()],
			['id' => '313', 'name' => 'FloCom Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '329', 'name' => '(C) T D Solutions', 'created_at' => now(), 'updated_at' => now()],
			['id' => '332', 'name' => 'Waco Bill ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '333', 'name' => 'GNJ Fiber', 'created_at' => now(), 'updated_at' => now()],
			['id' => '345', 'name' => 'Henkels   McCoy', 'created_at' => now(), 'updated_at' => now()],
			['id' => '355', 'name' => 'Huxley Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '356', 'name' => 'Charter Distribution  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '357', 'name' => 'Performance Trailers  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '359', 'name' => 'Salt River Project', 'created_at' => now(), 'updated_at' => now()],
			['id' => '362', 'name' => 'ImOn Communications  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '440', 'name' => 'Midwest Connections', 'created_at' => now(), 'updated_at' => now()],
			['id' => '452', 'name' => 'Nelson Telephone Cooperative', 'created_at' => now(), 'updated_at' => now()],
			['id' => '463', 'name' => 'Northern Arkansas Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '467', 'name' => 'Northwest Communications Cooperative', 'created_at' => now(), 'updated_at' => now()],
			['id' => '472', 'name' => '(C) Miller Pipeline', 'created_at' => now(), 'updated_at' => now()],
			['id' => '478', 'name' => 'Ontonagon County Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '482', 'name' => '(C) Otelco Telephone Walnut Grove  AL', 'created_at' => now(), 'updated_at' => now()],
			['id' => '500', 'name' => 'Pauley Construction AZ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '502', 'name' => 'Penasco Valley Telecommunications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '520', 'name' => 'Planters Telephone Cooperative', 'created_at' => now(), 'updated_at' => now()],
			['id' => '530', 'name' => 'Price Industrial Electric', 'created_at' => now(), 'updated_at' => now()],
			['id' => '532', 'name' => 'Prism Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '559', 'name' => 'SRT Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '566', 'name' => 'SEI Communications  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '576', 'name' => 'Midwest Cable Maintenance', 'created_at' => now(), 'updated_at' => now()],
			['id' => '580', 'name' => 'Ben Lomand Rural Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '583', 'name' => 'BNSF NE', 'created_at' => now(), 'updated_at' => now()],
			['id' => '586', 'name' => 'Cable One ID', 'created_at' => now(), 'updated_at' => now()],
			['id' => '600', 'name' => 'Southern Kansas Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '609', 'name' => 'Strata Networks', 'created_at' => now(), 'updated_at' => now()],
			['id' => '613', 'name' => 'Great Plains Communications Blair', 'created_at' => now(), 'updated_at' => now()],
			['id' => '624', 'name' => 'Murray Electric System', 'created_at' => now(), 'updated_at' => now()],
			['id' => '645', 'name' => '(C) Turnkey Network Solutions', 'created_at' => now(), 'updated_at' => now()],
			['id' => '655', 'name' => '(C) Valu Net LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '680', 'name' => 'Edwards Technical', 'created_at' => now(), 'updated_at' => now()],
			['id' => '693', 'name' => 'Charter Communications Operating  LLC NE', 'created_at' => now(), 'updated_at' => now()],
			['id' => '696', 'name' => 'Charter Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '705', 'name' => '(C) Utilicom', 'created_at' => now(), 'updated_at' => now()],
			['id' => '710', 'name' => 'Edwards Fiber Services', 'created_at' => now(), 'updated_at' => now()],
			['id' => '714', 'name' => 'Ervin Cable Construction  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '720', 'name' => 'Millennium', 'created_at' => now(), 'updated_at' => now()],
			['id' => '721', 'name' => 'Genesis Fiber Optic Splicing', 'created_at' => now(), 'updated_at' => now()],
			['id' => '727', 'name' => '(C) PCI Supply', 'created_at' => now(), 'updated_at' => now()],
			['id' => '728', 'name' => '(C) Truvista', 'created_at' => now(), 'updated_at' => now()],
			['id' => '731', 'name' => 'South Plains Telephone Cooperative  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '733', 'name' => 'USMILCOM', 'created_at' => now(), 'updated_at' => now()],
			['id' => '738', 'name' => 'McFarlane Trailer Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '747', 'name' => 'City Of Newberry  SC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '762', 'name' => '(C) Rogers Communications Partnership', 'created_at' => now(), 'updated_at' => now()],
			['id' => '788', 'name' => 'Ramstad Technologies', 'created_at' => now(), 'updated_at' => now()],
			['id' => '789', 'name' => 'Baker Hughes', 'created_at' => now(), 'updated_at' => now()],
			['id' => '805', 'name' => 'International Electric Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '809', 'name' => 'Lightlink  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '820', 'name' => 'Poulsen Trailer Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '823', 'name' => 'Nine Star Connect', 'created_at' => now(), 'updated_at' => now()],
			['id' => '827', 'name' => 'Cable Com LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '833', 'name' => 'Conduit Constructors', 'created_at' => now(), 'updated_at' => now()],
			['id' => '836', 'name' => '(C) Western Tel Com  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '848', 'name' => 'TelCom Construction Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '851', 'name' => 'Statton Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '855', 'name' => '(C) Sirah Contracting', 'created_at' => now(), 'updated_at' => now()],
			['id' => '856', 'name' => 'Shenandoah Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '857', 'name' => ' Scott County Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '860', 'name' => '(C) Ritter Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '861', 'name' => 'Reserve Telecommunications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '867', 'name' => 'Niels Fugal Sons Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '870', 'name' => 'Missouri Valley Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '883', 'name' => 'Telephone Switching Distributors  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '885', 'name' => 'Custom Cable Construction', 'created_at' => now(), 'updated_at' => now()],
			['id' => '886', 'name' => 'Producers Service Corp', 'created_at' => now(), 'updated_at' => now()],
			['id' => '888', 'name' => 'Socket Telecom', 'created_at' => now(), 'updated_at' => now()],
			['id' => '895', 'name' => 'Apachi Networks', 'created_at' => now(), 'updated_at' => now()],
			['id' => '900', 'name' => '(C) West Star TV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '902', 'name' => 'DataComm Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '906', 'name' => 'Hawkeye Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '908', 'name' => 'SEFNCO Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '910', 'name' => '(C) US Air Force PA', 'created_at' => now(), 'updated_at' => now()],
			['id' => '913', 'name' => 'Cable Wiring Specialist  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '916', 'name' => 'Huron Tel', 'created_at' => now(), 'updated_at' => now()],
			['id' => '917', 'name' => 'University Of Alabama', 'created_at' => now(), 'updated_at' => now()],
			['id' => '923', 'name' => 'Acme Communications  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '924', 'name' => 'Comtran Group', 'created_at' => now(), 'updated_at' => now()],
			['id' => '925', 'name' => 'MacFarland s', 'created_at' => now(), 'updated_at' => now()],
			['id' => '926', 'name' => 'Pigeon Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '929', 'name' => 'Falcon Cable Systems Company II  LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '932', 'name' => 'Superior Trailer', 'created_at' => now(), 'updated_at' => now()],
			['id' => '934', 'name' => 'Knology', 'created_at' => now(), 'updated_at' => now()],
			['id' => '936', 'name' => 'Interactive Productions', 'created_at' => now(), 'updated_at' => now()],
			['id' => '938', 'name' => 'Communications Supply Corporation', 'created_at' => now(), 'updated_at' => now()],
			['id' => '952', 'name' => 'TCS Communications  LLC FL', 'created_at' => now(), 'updated_at' => now()],
			['id' => '953', 'name' => '(C) Orlando Utitlity Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '954', 'name' => 'Cable Connections   Utilities', 'created_at' => now(), 'updated_at' => now()],
			['id' => '956', 'name' => 'FastTrack Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '964', 'name' => 'Elliott s Trailers   Carts', 'created_at' => now(), 'updated_at' => now()],
			['id' => '965', 'name' => '(C) Tularosa Basin Telephone Company (TBTC)', 'created_at' => now(), 'updated_at' => now()],
			['id' => '966', 'name' => '(C) Rogers Cable (AB)', 'created_at' => now(), 'updated_at' => now()],
			['id' => '967', 'name' => 'Falcon Cable Systems Company II LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '973', 'name' => 'Alabama Dept of Transportation', 'created_at' => now(), 'updated_at' => now()],
			['id' => '977', 'name' => 'Weatherford International SLS', 'created_at' => now(), 'updated_at' => now()],
			['id' => '978', 'name' => 'Becker Custom Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '979', 'name' => '(C) Push Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '985', 'name' => 'Finkel Holding  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '990', 'name' => 'NX Utilities ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '993', 'name' => 'A.M. Contracting', 'created_at' => now(), 'updated_at' => now()],
			['id' => '994', 'name' => 'Charter Communications   Missouri', 'created_at' => now(), 'updated_at' => now()],
			['id' => '997', 'name' => 'Selective Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '999', 'name' => 'G4S Technology LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1012', 'name' => 'Aero Communication', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1013', 'name' => 'West Tex Connect', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1014', 'name' => '(C) Know How Systems Global  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1018', 'name' => '(C) Mark James DVM', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1021', 'name' => 'Lumos Networks Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1026', 'name' => 'Daniel and David Helmuth', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1027', 'name' => 'Entergy', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1028', 'name' => 'Computer Techniques', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1029', 'name' => 'Comtech Technical Servies  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1031', 'name' => 'Columbia County Board of Commissioners', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1035', 'name' => 'City of Scottsburg', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1038', 'name' => 'CGG ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1055', 'name' => 'Comcast Cable Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1058', 'name' => 'Gerstner Electric', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1059', 'name' => 'Harlan Municipal Utilities', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1064', 'name' => '(C) Stratus Networks', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1067', 'name' => '(C) US Internet', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1072', 'name' => 'Poka Lambro Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1074', 'name' => 'UDI', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1078', 'name' => 'Communication Data Link', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1082', 'name' => 'Communication Construction Services Corp', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1100', 'name' => 'Syringa Networks   LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1102', 'name' => 'Flint Energies', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1103', 'name' => 'Cable One   Idaho Falls', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1104', 'name' => 'Oil Boss Rentals', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1109', 'name' => 'MCTV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1110', 'name' => 'FS3 Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1111', 'name' => 'BNSF   ND', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1120', 'name' => 'Indiana Michigan Power   AEP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1121', 'name' => 'Trican GeoTomo Microseismic Ltd', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1124', 'name' => 'Sonic.net', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1131', 'name' => 'K   W Underground', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1132', 'name' => 'Cypress Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1135', 'name' => 'PrimeTech Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1137', 'name' => 'Allan Dale Trailers   RV s', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1138', 'name' => '(C) P1 Group', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1139', 'name' => 'Alan Sfeir', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1148', 'name' => '(C) Thornhill Utility', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1149', 'name' => 'BNSF   Lincoln  Nebraska', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1164', 'name' => 'Suddenlink Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1166', 'name' => 'Capitol Renegade', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1170', 'name' => 'Jones Telecommunications  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1174', 'name' => 'City of Opelika   Accounts Payable', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1178', 'name' => '(C) System 3 Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1181', 'name' => '(C) Nexicom', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1182', 'name' => '(C) Prairieland Construction', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1187', 'name' => 'Alpha Grooming Products', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1189', 'name' => '(C) Terraspan Utility   Robby Hansen', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1190', 'name' => '(C) Ortelco', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1192', 'name' => 'Somerfield Cable TV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1205', 'name' => '(C) Wide Open West', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1206', 'name' => 'KAMO Power', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1211', 'name' => 'Cable One   Globe  AZ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1217', 'name' => 'Cumberland Electric Members Corp', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1227', 'name' => '(C) Thayer Power and Communication Line Construction', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1228', 'name' => 'Suncoast Fiber', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1236', 'name' => 'Mountrail Williams Electric Coop', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1243', 'name' => 'JME Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1246', 'name' => 'Rocky Moutain Contractors', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1247', 'name' => '(C) National Industrial Supply', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1253', 'name' => 'City of Franklin  TN', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1254', 'name' => 'Western Farmers Electric Cooperative', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1256', 'name' => ' Perley Cable Construction Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1258', 'name' => 'Wasatch Trailer Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1262', 'name' => '(C) Sandia National Laboratories', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1264', 'name' => '(C) Spiral Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1267', 'name' => 'Comtrac Services  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1268', 'name' => 'Maryland Broadband Cooperative', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1271', 'name' => 'Mississippi Power Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1273', 'name' => 'A   T Fiber Splicing Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1276', 'name' => 'All State Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1285', 'name' => 'WellSight Data LLC/Kipton Moravec', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1287', 'name' => 'D   D Power Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1299', 'name' => 'Project Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1302', 'name' => 'Grand River Dam Authority', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1307', 'name' => 'Franklin Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1309', 'name' => '(C) Dr. Rick Dalessandro', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1311', 'name' => 'BNSF   Stockton  CA', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1312', 'name' => 'Mid State Power LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1315', 'name' => 'MTCO Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1316', 'name' => 'Light Speed Integrated Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1320', 'name' => 'Absolute Control  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1329', 'name' => 'Buckeye CableSystem', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1337', 'name' => 'City of Suffolk', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1338', 'name' => 'Petromark Drilling  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1359', 'name' => 'Victory Custom Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1360', 'name' => 'Hinck Electric', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1364', 'name' => 'BHI Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1370', 'name' => 'Yakama Power', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1371', 'name' => 'Chain Electric', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1372', 'name' => 'Enterprise Electrical Services Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1374', 'name' => 'Frontier Communications   Michigan', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1379', 'name' => 'Wolin Mechanical   Electrical', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1380', 'name' => 'Fiber Technologies', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1381', 'name' => 'Cudd Pressure Control  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1386', 'name' => 'Optimum  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1391', 'name' => 'US 27 Motorsports   Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1392', 'name' => 'Speedy Gonzalez Construction', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1393', 'name' => 'Robertson Ditching', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1395', 'name' => 'Kitsap PUD', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1396', 'name' => 'CDB Utility Contractors', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1398', 'name' => 'Gilbert Network Solutions Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1399', 'name' => 'Murray City Corporation', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1401', 'name' => 'Iowa Network Services  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1403', 'name' => 'American Underground', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1404', 'name' => 'Seabery North America Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1405', 'name' => 'Anza Electric Cooperative  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1406', 'name' => 'Consolidated Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1410', 'name' => 'Southwest Oklahoma Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1412', 'name' => 'Siskiyou Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1413', 'name' => 'HP Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1432', 'name' => 'Double T Cable Services', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1434', 'name' => 'XIT Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1436', 'name' => 'US Air Force   Mountain Home', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1439', 'name' => 'Fiber Stock', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1445', 'name' => 'R   M Technical Services  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1446', 'name' => 'Power   Tel   Wisconsin', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1447', 'name' => 'Dubois Telephone Exchange Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1448', 'name' => 'Tambe Electric Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1452', 'name' => 'Mobil Satellite Technologies', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1456', 'name' => 'Joel Powell', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1476', 'name' => 'Supply Solutions  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1477', 'name' => 'Optonicus', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1485', 'name' => 'Niagara Mohawk Power Corp', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1493', 'name' => 'LM Services  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1500', 'name' => 'US Airforce   Minot  ND', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1502', 'name' => 'City Utilities of Springfield', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1508', 'name' => 'Spirit Communications', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1511', 'name' => 'US Air Force   Cannon AFB', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1515', 'name' => 'Anton Marano', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1516', 'name' => 'FiberComm', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1533', 'name' => 'TotelCom', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1536', 'name' => 'Waverly Communications Utility', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1537', 'name' => 'Kruse Underground Construction', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1540', 'name' => 'Viaero Wireless', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1543', 'name' => 'Cable One   TN', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1546', 'name' => 'Lakeland Energy', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1548', 'name' => 'Summit Broadband  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1550', 'name' => 'Elm City Trailer', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1553', 'name' => 'Above All Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1555', 'name' => 'KB Trailer Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1562', 'name' => 'Backbone Fiber Systems  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1570', 'name' => 'Stellco Enterprises LLC.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1572', 'name' => 'Dalton Utilities', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1578', 'name' => 'Cable One   Sioux City  IA', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1585', 'name' => 'Challenger Door', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1588', 'name' => 'CR Action Cable', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1591', 'name' => 'Master Electric Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1594', 'name' => 'TH Construction Co.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1595', 'name' => 'Griggs County Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1599', 'name' => 'Cox Enterprises  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1608', 'name' => 'Automotive Resources  Intl.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1610', 'name' => 'Clear Connection', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1612', 'name' => 'KC Fiber Optics Corp', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1616', 'name' => 'Glasford Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1619', 'name' => 'AEP Texas Inc dba AEP Texas', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1621', 'name' => 'Velocity.net Communications  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1630', 'name' => 'Pike Equipment and Supply Company  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1634', 'name' => 'Interstate Telecommunications Cooperative  Inv.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1638', 'name' => 'Sunny Island RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1640', 'name' => 'Weise Communications Ltd', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1641', 'name' => 'Carthage Water   Electric', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1642', 'name' => 'Custom Truck   Equipment  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1647', 'name' => 'Over Kill Motorsports', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1648', 'name' => 'Home Telephone Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1650', 'name' => 'inTech RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1666', 'name' => 'River City Recreation World', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1667', 'name' => 'Road Trip Camping', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1673', 'name' => 'Bay Country Communications  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1675', 'name' => 'Green Mountain Power', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1680', 'name' => 'FiberDocs', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1681', 'name' => 'Campbell Wright', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1682', 'name' => 'KODA Fiber Optics', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1683', 'name' => 'Chilhowee RV Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1690', 'name' => 'Empire Telephone Corp.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1700', 'name' => 'City of Woodbury', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1701', 'name' => 'Eastside RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1707', 'name' => 'SkyFiNet  LLC.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1713', 'name' => 'SCE G', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1717', 'name' => 'Byoplanet International LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1719', 'name' => 'Nature Coast RV INC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1720', 'name' => 'Missouri Teardrop Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1722', 'name' => 'Tri County EMC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1727', 'name' => 'Tetra Tech Utility Construction  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1728', 'name' => 'Tiya Support Services  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1729', 'name' => 'Gardner Telecommunications  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1730', 'name' => 'HTC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1737', 'name' => 'Bumgarner Camping Center Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1738', 'name' => 'Decisive Communications Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1743', 'name' => 'Moore s RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1744', 'name' => 'Haydocy Airstream   RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1748', 'name' => 'Comcast  Kansas City', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1752', 'name' => 'West River Cooperative', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1756', 'name' => 'Hartleys Auto   RV Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1767', 'name' => 'American Broadband Services  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1770', 'name' => 'CI Utilities', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1772', 'name' => 'Confederated Tribes of the Colville', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1773', 'name' => 'AT T Dallas', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1774', 'name' => 'Acres RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1783', 'name' => 'Charter Communications SC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1785', 'name' => 'B   B RV Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1786', 'name' => 'TAC RV Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1787', 'name' => ' Nevada Power Company dba NV Energy', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1788', 'name' => 'Access RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1789', 'name' => 'Cedar City RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1790', 'name' => 'Roth RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1791', 'name' => 'Dad s Camper Outlet', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1792', 'name' => 'Princess Craft', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1794', 'name' => 'Team One Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1795', 'name' => 'Momot Trailer Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1804', 'name' => 'Elk River RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1809', 'name' => 'Southland RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1811', 'name' => 'Tom s Camperland', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1819', 'name' => 'Sheridan Search   Rescue', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1823', 'name' => 'Mount Comfort RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1824', 'name' => 'Sub Surfaces  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1841', 'name' => 'Northtown Motorhomes', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1851', 'name' => 'Integral Blue', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1853', 'name' => 'Chico Truck   RV  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1859', 'name' => 'Communication Innovators', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1860', 'name' => 'Western Utility', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1864', 'name' => 'Filtration Technology Corporation', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1865', 'name' => 'Texas Steel Industries LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1877', 'name' => 'Albany Mutual Telephone', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1882', 'name' => 'Charter Communications Orlando', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1883', 'name' => 'Go Play RV Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1892', 'name' => 'ProComm LLC.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1898', 'name' => 'Emkay INC. Trust', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1899', 'name' => 'Polaris West', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1903', 'name' => 'LCRA', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1904', 'name' => 'Southwestern Electric Power Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1906', 'name' => 'Cotton Electric CO OP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1912', 'name' => 'S   T Communincations', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1918', 'name' => 'Electrical Production Services', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1920', 'name' => 'Mud Lake Telephone Co Op Association', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1921', 'name' => 'Eva Pennington', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1923', 'name' => ' Army Contracting Command  APG', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1924', 'name' => 'Great River Energy ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1926', 'name' => 'Innovated Fiber Technologies', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1927', 'name' => 'AZCI.net  LLC. ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1932', 'name' => 'Quanta Telecommunication Services LLC.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1933', 'name' => 'Murphy Communications  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1935', 'name' => 'Loren Borkholder', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1937', 'name' => 'Nex Gen Fiber Services', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1938', 'name' => 'Apex Telecom Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1951', 'name' => 'Nohr s RV Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1952', 'name' => 'Hancock Telephone Co.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1953', 'name' => 'Professional Leasing Services', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1955', 'name' => 'RV Outpost', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1957', 'name' => 'Ringgold Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1958', 'name' => 'Dale Borkholder', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1959', 'name' => 'Roulottes Ste Anne', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1960', 'name' => 'Kearney s Enterprises Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1961', 'name' => 'Bankston Motor Homes   Huntsville', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1964', 'name' => 'Leo s Vacation Center  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1965', 'name' => 'Ketchikan Public Utillies Telecom', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1966', 'name' => 'Northeast Cable Construction LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1967', 'name' => 'Racetrack RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1968', 'name' => 'Curtis Trailers  Inc   Portland', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1969', 'name' => 'RLH Equipment Leasing  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1970', 'name' => 'Fun Town RV Dallas  LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1971', 'name' => 'Fun Town RV Purcell  LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1972', 'name' => 'Fun Town RV San Angelo  LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1973', 'name' => 'Fun Town RV Denton  LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1974', 'name' => 'Fun Town RV Houston  LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1975', 'name' => 'Fun Town RV Cleburne  LP', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1976', 'name' => 'NORTHERN TELEPHONE', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1980', 'name' => 'Bankston Motor Homes   Albertville', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1981', 'name' => 'Bankston Motor Homes   Nashville', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1983', 'name' => 'Hutterian Broadband Network Inc. ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1984', 'name' => 'Miller RV Sales', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1985', 'name' => 'Holiday on Wheels', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1986', 'name' => 'Jerry s Camping Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1987', 'name' => 'Kamper City', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1988', 'name' => 'D H RV Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1989', 'name' => 'RV World', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1990', 'name' => 'City of Tupelo', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1991', 'name' => 'Bankston Motor Homes   Florence', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1993', 'name' => 'Clear Creek RV Center   Silverdale', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1995', 'name' => 'Tiffin Motorhomes', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1996', 'name' => 'Rex   Sons RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1997', 'name' => '1000 Islands RV Centre', 'created_at' => now(), 'updated_at' => now()],
			['id' => '1998', 'name' => 'CHALLENGER TECHNICAL MANAGEMENT  INC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2000', 'name' => 'Revy RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2002', 'name' => 'Travelcamp RV   Jacksonville', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2003', 'name' => 'Mattas Motors  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2010', 'name' => 'Hemlock Hill RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2011', 'name' => 'Sunshine RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2012', 'name' => 'Gerton Auto Sales  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2015', 'name' => 'Accelerated Communications   Construction', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2016', 'name' => 'Western Skies RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2017', 'name' => 'Paonia Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2018', 'name' => 'Oak Centre RV Mall', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2020', 'name' => 'Inter Community Telephone Co. LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2021', 'name' => 'Modern Edge Technologies', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2024', 'name' => 'Q2 Fiber Communications  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2027', 'name' => 'Indianola Municipal Utilities', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2028', 'name' => 'TerryTown RV Superstore', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2029', 'name' => 'TradeWinds RV Center', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2030', 'name' => 'Travelcamp RV   Orange Park', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2031', 'name' => 'National RV Detroit', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2036', 'name' => 'Fiberpro LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2037', 'name' => 'NfinityLink Communications  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2045', 'name' => 'Cable One Vincennes       ', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2048', 'name' => 'Little Guy Trailers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2049', 'name' => 'Sherrod RV Center  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2055', 'name' => 'H   E Equipment Services', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2057', 'name' => 'Nushagak Electric   Telephone Cooperative  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2058', 'name' => 'Colton RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2061', 'name' => 'Drew Lyons', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2066', 'name' => 'Chickadee Wireless  INC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2068', 'name' => 'Russ   Mary O Blenes', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2069', 'name' => 'Public Service Company of Oklahoma', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2071', 'name' => 'Lantek Fiber Optic Service  Inc', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2072', 'name' => 'Zamar Technologies LLC.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2073', 'name' => 'Nelsons  Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2076', 'name' => 'Oil   Gas Process Solutions', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2077', 'name' => 'Nishna Valley Cycle INC.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2082', 'name' => 'Tatum Court Creamer', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2083', 'name' => 'Omaha Public Power Distric', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2084', 'name' => 'Forked Deer Electric Co op', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2086', 'name' => 'Cable Telecommunications Services Incorporated', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2087', 'name' => 'Joink LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2089', 'name' => 'Elite Splicing  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2092', 'name' => 'Wave Broadband', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2093', 'name' => 'Pattersonville Telephone Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2097', 'name' => 'Precision Fiber Optics', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2102', 'name' => 'Upper Cumberland Electric Membership Corporation', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2103', 'name' => '4C Company', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2104', 'name' => 'Bayside Outdoors', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2105', 'name' => 'Bob Hurley RV LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2106', 'name' => 'Tim Bishop', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2107', 'name' => 'Tim s RV Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2108', 'name' => 'Van City RV   Montana', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2109', 'name' => 'Van City RV   Colorado', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2110', 'name' => 'Van City RV   Missouri', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2111', 'name' => 'Aloha RV', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2112', 'name' => 'RV Four Seasons   Wheat Ridge', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2113', 'name' => 'RV Four Seasons   Loveland', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2114', 'name' => 'Gerzeny s RV World   Nokomis', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2115', 'name' => 'Gerzeny s RV World   Lakeland', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2116', 'name' => 'Gerzeny s RV World   Bradenton', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2117', 'name' => 'Gerzeny s RV World   Fort Myers', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2118', 'name' => 'Mercaterra Atlantic  LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2120', 'name' => 'Uncharted Recreation', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2121', 'name' => 'Bonner Sports', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2122', 'name' => 'Spare Time Fun Center LLC', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2123', 'name' => 'inTech RV Power Program', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2124', 'name' => 'inTech RV Consigned/Offiste Stock', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2125', 'name' => 'Jeffry Knight Inc.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2126', 'name' => 'Unitec', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2127', 'name' => 'Station Park Honda', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2128', 'name' => 'Van City RV   Nevada', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2130', 'name' => 'Imperial Camper', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2131', 'name' => 'BCRV Sales INC.', 'created_at' => now(), 'updated_at' => now()],
			['id' => '2132', 'name' => 'Gem State Utilities and Construction', 'created_at' => now(), 'updated_at' => now()]
		]);
	}
}
